[renderer]
samples = 64
no-direct-emitter = false
integrator = "pt-direct"

[film]
resolution = [960, 540]
output = "hdr"

[sky]
type = "uniform"
color = [0, 0, 0]

[camera]
type = "ideal-pinhole"
fov = 39.3077
[[camera.transform]]
type = "look-at"
origin = [0, 110, -500]
target = [0, 60, 0]
up = [0, 1, 0]

[[light]]
type = "area"
object = "light"
emission = [15, 13, 11]

[[object]]
mesh = "sphere"
material = "lambert"
[[object.transform]]
type = "translate"
vector = [-120, 25, 0]

[[object]]
mesh = "sphere"
material = "glossy1"
[[object.transform]]
type = "translate"
vector = [-60, 25, 0]

[[object]]
mesh = "sphere"
material = "glossy5"
[[object.transform]]
type = "translate"
vector = [0, 25, 0]

[[object]]
mesh = "sphere"
material = "glossy10"
[[object.transform]]
type = "translate"
vector = [60, 25, 0]

[[object]]
mesh = "sphere"
material = "glossy20"
[[object.transform]]
type = "translate"
vector = [120, 25, 0]

[[object]]
mesh = "quad"
[[object.transform]]
type = "scale"
vector = [200, 1, 100]

[[object]]
mesh = "quad"
material = "floor"
[[object.transform]]
type = "scale"
vector = [200, 1, 100]
[[object.transform]]
type = "translate"
vector = [0, 0, 100]
[[object.transform]]
type = "axis-angle"
axis = [1, 0, 0]
angle = -80
[[object.transform]]
type = "translate"
vector = [0, 0, 100]

[[object]]
name = "light"
mesh = "quad"
[[object.transform]]
type = "axis-angle"
axis = [1, 0, 0]
angle = 180
[[object.transform]]
type = "scale"
vector = [100, 1, 7]
[[object.transform]]
type = "translate"
vector = [0, 120, 0]

[[material]]
name = "floor"
type = "lambert"
albedo = [0.5, 0.5, 0.4]

[[material]]
name = "lambert"
type = "lambert"
albedo = [0.5, 0.5, 0.5]

[[material]]
name = "glossy1"
type = "ggx"
reflectance = [1.0, 1.0, 1.0]
roughness = 0.8
ior = 100000

[[material]]
name = "glossy5"
type = "ggx"
reflectance = [1.0, 1.0, 1.0]
roughness = 0.6
ior = 100000

[[material]]
name = "glossy10"
type = "ggx"
reflectance = [1.0, 1.0, 1.0]
roughness = 0.4
ior = 100000

[[material]]
name = "glossy20"
type = "ggx"
reflectance = [1.0, 1.0, 1.0]
roughness = 0.2
ior = 100000

[[mesh]]
name = "quad"
type = "obj"
path = "models/simple/quad.obj"

[[mesh]]
name = "sphere"
type = "sphere"
radius = 25
